<?php

// Escrow Info Form Fields
$fields = [
    'Ajax Action' => [
        'id' => 'EscrotEscrowAjaxAction',
        'name' => 'action',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-12',
        'callback' => 'escrot_insert_escrow',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    'Ajax Nonce' => [
        'id' => 'EscrotEscrowAjaxNonce',
        'name' => 'nonce',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-12',
        'callback' => wp_create_nonce('escrot_escrow_nonce'),
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    'Escrow ID' => [
        'id' => 'EscrotEscrowID',
        'name' => 'escrow_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-12',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    __('Ref ID', 'escrowtics') => [
        'id' => 'EscrotEscrowRefID',
        'name' => 'ref_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-12',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    __('User (Payer)', 'escrowtics') => [
        'id' => 'EscrotEscrowPayer',
        'name' => 'payer',
        'type' => escrot_is_front_user() ? 'text' : 'select',
        'placeholder' => '',
        'div-class' => escrot_is_front_user() ? 'col-md-12' : 'col-md-6',
        'callback' => escrot_is_front_user() ? '' : escrot_users(),
        'display' => escrot_is_front_user() ? false : true,
        'help-info' => '',
        'required' => escrot_is_front_user() ? false : true,
    ],
    __('User (Earner)', 'escrowtics') => [
        'id' => 'EscrotEscrowEarner',
        'name' => 'earner',
        'type' => escrot_is_front_user() ? 'text' : 'select',
        'placeholder' => __('Enter Earner Username', 'escrowtics'),
        'div-class' => escrot_is_front_user() ? 'col-md-12' : 'col-md-6',
        'callback' => escrot_is_front_user() ? '' : escrot_users(),
        'display' => true,
        'help-info' => '',
        'required' => true,
    ],
];

include ESCROT_PLUGIN_PATH . "templates/forms/form-fields/form-fields-manager.php";
